version: "3"

services:
  nginx:
    image: nginx:1.15.5
    ports:
      - "80:80"
      - "443:443"
    hostname: nginx
    networks:
      - y3d
    restart: always
    volumes:
      - $PWD:/usr/share/nginx/html
networks:
  y3d:
    external: true
